Repository AY2425S1-CS2103T-W12-1/tp, pull requests merged in 2024-11, with the labels that each got.

#123 Fix alpha bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: alpha-bug

#125 Fix more alpha bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#113 Update UG to include search command
  docs/UserGuide.md
  docs/images/searchCommandSuccess.png
  src/main/java/seedu/address/logic/commands/SearchCommand.java
Labels: alpha-bug

#126 Add renameTag format error messages and correct UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RenameTagCommand.java
  src/main/java/seedu/address/logic/parser/RenameTagParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RenameTagCommandTest.java
  src/test/java/seedu/address/logic/commands/SocialMediaCommandTest.java
  src/test/java/seedu/address/logic/parser/RenameTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SocialMediaCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#115 Fix help command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug

#132 change helpMessage image in userGuide
  docs/images/helpMessage.png
Labels: alpha-bug

#130 Improve branch Command documentation
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/BackupCommand.java
  src/test/java/seedu/address/logic/commands/BackupCommandTest.java
Labels: alpha-bug

#134 Branch alphabugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/SocialMediaCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SocialMediaCommandParserTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: alpha-bug

#229 Fix some documentation bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#227 Fix backup command bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/BackupCommand.java
  src/test/java/seedu/address/logic/commands/BackupCommandTest.java
Labels: severity.Medium
